### ISSUE TITLE
Question about Local Branch Predictor

### ISSUE THREAD

**Issue by itviewer** [jlpteaching/dinocpu#141]
According to Scott McFarling’s [paper](http://american.cs.ucdavis.edu/academic/readings/papers/mcfarling.pdf) , is it better to rename [Local Predictor](https://github.com/jlpteaching/dinocpu/blob/main/src/main/scala/components/branchpred.scala#L74) to Bimodal Predictor, so that it can be distinguished from Local History Predictor?

**Comment by powerjg** [comment]
Thanks for the comment! I agree that Bimodal is a more precise name. I chose "local predictor" because it followed from the class lectures. In the class I teach, we tend to not focus on much more than the difference between "local" history (i.e., per-pc) and global history (i.e., based on the global branch history). I'm going to close this for now as I have no concrete plans to make the update. But, I would be happy to review a pull request with more precise names :).
